name: Build XMRig

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
        with:
          repository: xmrig/xmrig

      - name: Build
        run: |
          mkdir build
          touch build/xmrig

      - name: Store generated file
        uses: actions/upload-artifact@v2
        env: 
          XMRIG_VERSION: $(cat version.h | grep -Eo "APP_VERSION\s+\"(.+?)\"" | awk -F "\"" '{print $2}')
        with:
          name: xmrig-${{env.XMRIG_VERSION}}
          path: build/xmrig
