name: Build XMRig

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: alpine:3.12.1

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
        with:
          repository: xmrig/xmrig

      - name: Build
        run: |
          touch build/xmrig
          echo "::set-env name=XMRIG_VERSION::$(cat version.c | grep -Eo "APP_VERSION\s+\"(.+?)\"" | awk -F "\"" '{print $2}')"

      - name: Store generated file
        uses: actions/upload-artifact@v2
        with:
          name: xmrig-${{ env.XMRIG_VERSION }}
          path: build/xmrig
